# config.yaml (add-on)
name: "Surikat Editor Homeassistant"
description: "Surikat editor plugin for Homeassistant"
version: "1.0.14"
slug: "surikat-editor"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000
options:
  mqtt_host: "mqtt://localhost"
  mqtt_port: 1883
  mqtt_topic: "frigate/events"
  mqtt_user: "user"
  mqtt_password: "password"
  network: "wifi"
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_topic: str
  mqtt_user: str
  mqtt_password: str
  network:
    type: select
    options:
      - wifi
      - poe
map:
  config:
    target: /config
    readonly: false