name: "Surikat Homeassistant"
description: "Surikat plugin for Homeassistant"
version: "1.0.14"
slug: "surikat-editor"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000
options:
  mqtt_host: "mqtt://localhost"
  mqtt_port: 1883
  mqtt_topic: "frigate/events"
  mqtt_user: "user"
  mqtt_password: "password"
  default_name: "password"
  network_type: "wifi"   # Valeur par défaut
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_topic: str
  mqtt_user: str
  mqtt_password: str
  default_name: str
  network_type:
    type: str
    description: "Choisissez le type de réseau"
    enum:
      - wifi
      - poe
map:
  config:
    target: /config
    readonly: false
advanced:
  steps:
    - title: "Étape 1: Network"
      description: "Configurez le type de connexion réseau"
      fields:
        - name: "network_type"
          type: "select"
          label: "Type de réseau"
          options:
            - value: "wifi"
              label: "Wi-Fi"
            - value: "poe"
              label: "PoE"
