# config.yaml (add-on)
name: "Surikat Editor Homeassistant"
description: "Surikat editor config plugin for Homeassistant"
version: "1.0.14"
slug: "surikat"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000
options:
  connection_type: "POE"  # Valeur par défaut
  client: "client name"
  mqtt_host: "mqtt://localhost"
  mqtt_port: 1883
  mqtt_topic: "frigate/events"
  mqtt_user: "user"
  mqtt_password: "password"
schema:
  connection_type:
      type: str
      description: "Choisissez le type de connexion"
      selector:
        select:
          options:
            - POE
            - WIFI
  client: str
  mqtt_host: str
  mqtt_port: int
  mqtt_topic: str
  mqtt_user: str
  mqtt_password: str
map:
  config:
    target: /config
    readonly: false