# config.yaml (add-on)
name: "Surikat Editor Homeassistant"
description: "Surikat editor config plugin for Homeassistant"
version: "1.0.14"
slug: "surikat"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000

# Options disponibles dans l'UI
options:
  connection_type: "POE"         # Liste déroulante POE/WIFI
  enable_logging: true           # Booléen pour activer/désactiver le logging
  device_name: "Surikat"         # Nom du périphérique
  mqtt_host: "mqtt://localhost"
  mqtt_port: 1883
  mqtt_topic: "frigate/events"
  mqtt_user: "user"
  mqtt_password: "password"

# Définition des types et selecteurs pour l'UI
schema:
  connection_type:
    type: str
    description: "Choisissez le type de connexion"
    selector:
      select:
        options:
          - POE
          - WIFI
  enable_logging:
    type: bool
    description: "Activer le logging pour Surikat Editor"
  device_name:
    type: str
    description: "Nom du périphérique utilisé par l'add-on"
  mqtt_host: str
  mqtt_port: int
  mqtt_topic: str
  mqtt_user: str
  mqtt_password: str

# Mapping vers le système de fichiers
map:
  config:
    target: /config
    readonly: false
